---
name: text-analysis
break: true
indent: 4
---

# Learn more about GatorGrader and its supported checks by visiting this web site:
# https://github.com/GatorEducator/gatorgrader

# Explanation:
# --> a check without an "--exact" runs a count for an entity as an "at least"
# --> checks below a file in a specified directory are for that specific file and directory
# --> checks that appear stand-alone are for an entire Git repository

# --> check the Python program
textanalysis/textanalysis/main.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "Option(None)" --count 2 --exact
    MatchFileFragment --fragment "from pathlib import Path" --count 1 --exact
    CountMultipleLineComments --language Python --count 2 --exact
    CountSingleLineComments --language Python --count 17

# --> confirm existence of a file
textanalysis/graphics/set-visualization-generated.png:
    ConfirmFileExists

# --> confirm existence of a file
textanalysis/graphics/set-visualization-input.png:
    ConfirmFileExists

# --> confirm existence of a file
textanalysis/text/generated_one.txt:
    ConfirmFileExists

# --> confirm existence of a file
textanalysis/text/generated_two.txt:
    ConfirmFileExists

# --> confirm existence of a file
textanalysis/text/input_one.txt:
    ConfirmFileExists

# --> confirm existence of a file
textanalysis/text/input_two.txt:
    ConfirmFileExists

# --> check the Python program
textanalysis/textanalysis/extract.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountMultipleLineComments --language Python --count 2
    CountSingleLineComments --language Python --count 7

# --> check the Python program
textanalysis/textanalysis/visualize.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountMultipleLineComments --language Python --count 2
    CountSingleLineComments --language Python --count 5

# --> check the technical writing for various characteristics
writing/reflection.md:
    ConfirmFileExists
    CountFileWords --count 500
    CountMarkdownTags --tag "heading" --count 16
    CountMarkdownTags --tag "code_block" --count 5
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact

# --> check that the number of commits in the Git repository is beyond a threshold
CountCommits --count 10
